# Generated by Django 5.1 on 2024-09-02 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField(default=0)),
                ('naturalidade', models.CharField(default='Russas', max_length=20)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9)),
                ('profissao', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=30)),
                ('n_rg', models.CharField(max_length=9)),
                ('orgao_exp', models.CharField(max_length=20)),
                ('data_expedicao', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('titulo', models.CharField(max_length=11)),
                ('carteira_trabalho', models.CharField(blank=True, max_length=10, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('registro_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('certidao', models.CharField(choices=[('certidao_casamento', 'Certidão de Casamento'), ('certidao_nascimento', 'Certidão de Nascimento')], max_length=20)),
                ('folhas', models.CharField(blank=True, max_length=10, null=True)),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('data_emissao', models.DateField()),
                ('outras_instituicoes', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, null=True)),
                ('detalhes_outros_instituicoes', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cônjuge',
            },
        ),
        migrations.CreateModel(
            name='Dependentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField(default=0)),
                ('naturalidade', models.CharField(default='Russas', max_length=20)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9)),
                ('endereco', models.CharField(max_length=30)),
                ('n_rg', models.CharField(max_length=9)),
                ('orgao_exp', models.CharField(max_length=20)),
                ('data_expedicao', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('certidao', models.CharField(choices=[('certidao_nascimento', 'Certidão de Nascimento')], max_length=20)),
                ('folhas', models.CharField(blank=True, max_length=10, null=True)),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('data_emissao', models.DateField()),
                ('registro_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('outras_instituicoes', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, null=True)),
                ('detalhes_outros_instituicoes', models.CharField(blank=True, max_length=255, null=True)),
                ('estuda', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, null=True)),
                ('serie', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Dependente',
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastramento', models.DateField()),
                ('data_inclusao', models.DateField()),
                ('nome', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('idade', models.PositiveIntegerField(default=0)),
                ('naturalidade', models.CharField(default='Russas', max_length=20)),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=9)),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo'), ('uniao_estavel', 'União estável')], max_length=13)),
                ('profissao', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=30)),
                ('n_rg', models.CharField(max_length=9)),
                ('orgao_exp', models.CharField(max_length=20)),
                ('data_expedicao', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
                ('titulo', models.CharField(max_length=11)),
                ('carteira_trabalho', models.CharField(blank=True, max_length=10, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('registro_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('certidao', models.CharField(choices=[('certidao_casamento', 'Certidão de Casamento'), ('certidao_nascimento', 'Certidão de Nascimento')], default='certidao_casamento', max_length=20)),
                ('folhas', models.CharField(blank=True, max_length=10, null=True)),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('data_emissao', models.DateField()),
                ('outras_instituicoes', models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=3, null=True)),
                ('detalhes_outros_instituicoes', models.CharField(blank=True, default='Não participa', max_length=255, null=True)),
                ('conjuge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='pessoa.conjuge')),
                ('dependente', models.ManyToManyField(blank=True, related_name='pessoas', to='pessoa.dependentes')),
            ],
            options={
                'verbose_name': 'Pessoa',
            },
        ),
    ]
